/**
 * Generates responsive image variants for the assets that dominate page load.
 *
 * The farm background used to ship as a single 877 KB PNG that every screen
 * rendered on first paint. This emits AVIF/WebP/JPEG variants at several widths
 * plus a manifest that `ResponsiveImage.jsx` turns into a <picture> srcset.
 *
 * Sources live in frontend/assets-source so Vite never sees them; only the
 * generated variants under src/assets reach the bundle.
 *
 * Run with:  npm run optimize:assets
 */

import { existsSync, statSync } from 'node:fs';
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, '..', 'assets-source');
const assets = resolve(here, '..', 'src', 'assets');

const JOBS = [
  {
    id: 'farmBackground',
    file: 'Gemini_Generated_Image_o4e5bbo4e5bbo4e5.png',
    dir: 'farm-background',
    widths: [640, 1024, 1376],
    opaque: true,
  },
  {
    id: 'pigDashboard',
    file: 'Gemini_Generated_Image_92oun292oun292ou-removebg-preview.png',
    dir: 'pig-dashboard',
    widths: [768, 1354],
    opaque: false,
  },
  {
    id: 'pigLogin',
    file: '2e388bda-a6fa-4911-bcea-0e3aaa26ed7f-removebg-preview.png',
    dir: 'pig-login',
    widths: [500],
    opaque: false,
  },
];

const kb = (bytes) => `${(bytes / 1024).toFixed(1)} KB`;

async function emit(job, width, nativeWidth) {
  const target = Math.min(width, nativeWidth);
  const base = join(assets, job.dir, `${job.id}-${target}`);
  const resize = () => sharp(join(source, job.file), { failOn: 'none' }).resize({ width: target });

  const written = [];

  const avif = await resize().avif({ quality: 62, effort: 5 }).toBuffer();
  await writeFile(`${base}.avif`, avif);
  written.push({ format: 'avif', width: target, bytes: avif.length });

  const webp = await resize().webp({ quality: 70, effort: 5 }).toBuffer();
  await writeFile(`${base}.webp`, webp);
  written.push({ format: 'webp', width: target, bytes: webp.length });

  if (job.opaque) {
    const jpeg = await resize().jpeg({ quality: 78, mozjpeg: true }).toBuffer();
    await writeFile(`${base}.jpg`, jpeg);
    written.push({ format: 'jpg', width: target, bytes: jpeg.length });
  } else {
    const png = await resize().png({ compressionLevel: 9, palette: true }).toBuffer();
    await writeFile(`${base}.png`, png);
    written.push({ format: 'png', width: target, bytes: png.length });
  }

  return written;
}

async function run() {
  const manifest = {};

  for (const job of JOBS) {
    const outDir = join(assets, job.dir);
    await rm(outDir, { recursive: true, force: true });
    await mkdir(outDir, { recursive: true });

    const original = join(source, job.file);
    if (!existsSync(original)) {
      throw new Error(`missing source image: ${original}`);
    }
    const sourceBytes = statSync(original).size;
    const { width: nativeWidth } = await sharp(original).metadata();

    console.log(`\n${job.id}  (${job.file} - ${kb(sourceBytes)}, ${nativeWidth}px wide)`);

    const variants = [];
    for (const width of job.widths) {
      for (const entry of await emit(job, width, nativeWidth)) {
        variants.push(entry);
        console.log(`  ${entry.format.padEnd(4)} ${String(entry.width).padStart(4)}w  ${kb(entry.bytes)}`);
      }
    }

    const group = (format) => variants.filter((v) => v.format === format);
    const rel = (v, format) => `./${job.dir}/${job.id}-${v.width}.${format}`;
    const fallbackFormat = job.opaque ? 'jpg' : 'png';
    manifest[job.id] = {
      alt: job.id === 'farmBackground' ? 'Farm Background' : 'Pig Character',
      avif: group('avif').map((v) => ({ width: v.width, url: rel(v, 'avif') })),
      webp: group('webp').map((v) => ({ width: v.width, url: rel(v, 'webp') })),
      fallback: group(fallbackFormat).map((v) => ({ width: v.width, url: rel(v, fallbackFormat) })),
    };
  }

  const body = Object.entries(manifest)
    .map(([id, entry]) => {
      const set = (list) =>
        list.map((v) => `      { width: ${v.width}, url: new URL('${v.url}', import.meta.url).href },`).join('\n');
      return [
        `  ${id}: {`,
        `    alt: '${entry.alt}',`,
        `    avif: [`,
        set(entry.avif),
        `    ],`,
        `    webp: [`,
        set(entry.webp),
        `    ],`,
        `    fallback: [`,
        set(entry.fallback),
        `    ],`,
        `  },`,
      ].join('\n');
    })
    .join('\n');

  const file = `// Generated by scripts/optimize-assets.mjs - do not edit by hand.
export const responsiveImages = {
${body}
};
`;

  await writeFile(join(assets, 'imageManifest.js'), file);
  console.log(`\nwrote ${join(assets, 'imageManifest.js')}`);

  await optimizeIcons();
}

/**
 * The PWA icons shipped as uncompressed 32-bit PNGs (~138 KB for a flat 512px
 * illustration). Re-encoding them with a palette in place keeps the same
 * dimensions and alpha, at a fraction of the size.
 */
async function optimizeIcons() {
  const dir = resolve(here, '..', 'public', 'icons');
  if (!existsSync(dir)) return;

  console.log('\npublic/icons');
  for (const file of (await readdir(dir)).filter((f) => f.endsWith('.png'))) {
    const path = join(dir, file);
    const before = statSync(path).size;
    const png = await sharp(path)
      .png({ compressionLevel: 9, palette: true, quality: 100, effort: 10 })
      .toBuffer();
    if (png.length < before) {
      await writeFile(path, png);
      console.log(`  ${file.padEnd(24)} ${kb(before)} -> ${kb(png.length)}`);
    } else {
      console.log(`  ${file.padEnd(24)} ${kb(before)} (already optimal)`);
    }
  }
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});